name: Html Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "latest"

      - name: Install HaxeFlixel and other libraries
        run: |
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hxdiscord_rpc

      - name: Build Project
        run: |
          haxelib run lime build html5

      - name: Archive built project
        uses: actions/upload-artifact@v4
        with:
          name: built-project
          path: export/html5/bin
